name: CI - develop - slow controller-api-4

on:
  schedule:
    # Run every day at midnight. Add another cron entry to run at a different time.
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ihmcrobotics/valkyrie/.github/workflows/source-dep-GradleCI-base.yml@develop
    with:
      test-category: "controller-api-slow-4"

