name: CI - develop - humanoid-rough-terrain

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  schedule:
    # Run every day at midnight. Add another cron entry to run at a different time.
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  checks: write
  contents: read

jobs:
  build:
    uses: ihmcrobotics/valkyrie/.github/workflows/source-dep-GradleCI-base.yml@develop
    with:
      test-category: "humanoid-rough-terrain"
      open-robotics-branch: "develop"
