name: Gradle test (fast)

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:

permissions:
  checks: write
  contents: read

jobs:
  hw-drivers-fast:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
    secrets:
      ROSIE_PERSONAL_ACCESS_TOKEN: ${{ secrets.ROSIE_PERSONAL_ACCESS_TOKEN }}
    with:
      test-category: 'fast'
      extra-repos: '["ihmc-open-robotics-software"]'
      requires-self-hosted: true
      timeout-minutes: 65
