name: CI - main - humanoid-obstacle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-humanoid-obstacle:
    uses: ihmcrobotics/valkyrie/.github/workflows/main-GradleCI-base.yml@main
    with:
      test-category: "humanoid-obstacle"
