name: CI - main - category fast

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-fast:
    uses: main-GradleCI-base.yml@main
    secrets:
      testCategory: ${{ fast }}
