# This workflow is used as the base for the other workflows mean to be run on the main branch.
name: CI - main - base

on:
  workflow_call:
    inputs:
      secrets:
        testCategory:
          required: true

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: 8.5

      - name: Gradle test fast
        run: gradle test -Pcategory=fast
      - name: Gradle test controller-api
        run: gradle test -Pcategory=controller-api
      - name: Gradle test controller-api-2
        run: gradle test -Pcategory=controller-api-2
      - name: Gradle test humanoid-flat-ground
        run: gradle test -Pcategory=humanoid-flat-ground
      - name: Gradle test humanoid-obstacle
        run: gradle test -Pcategory=humanoid-obstacle
      - name: Gradle test humanoid-push-recovery
        run: gradle test -Pcategory=humanoid-push-recovery
      - name: Gradle test humanoid-rough-terrain
        run: gradle test -Pcategory=humanoid-rough-terrain
      - name: Gradle test humanoid-toolbox
        run: gradle test -Pcategory=humanoid-toolbox
