name: CI - main - controller-api-2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-controller-api-2:
    uses: ihmcrobotics/valkyrie/.github/workflows/main-GradleCI-base.yml@main
    with:
      test-category: "controller-api-2"
