name: CI - main - humanoid-flat-ground

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-humanoid-flat-ground:
    uses: ihmcrobotics/valkyrie/.github/workflows/version-dep-GradleCI-base.yml@main
    with:
      test-category: "humanoid-flat-ground"
