# This workflow is used as the base for the other workflows mean to be run on the main branch.
name: CI - main - base

on:
  workflow_call:

permissions:
  contents: read

jobs:
  main-setup-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: 8.5
