name: CI - main - slow humanoid-rough-terrain

on:
  schedule:
    # Run every day at midnight. Add another cron entry to run at a different time.
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-slow-humanoid-rough-terrain:
    uses: ihmcrobotics/valkyrie/.github/workflows/version-dep-GradleCI-base.yml@main
    with:
      test-category: "humanoid-rough-terrain-slow"

