name: CI - main - fast

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-fast:
    uses: ihmcrobotics/valkyrie/.github/workflows/main-GradleCI-base.yml@main
    with:
      test-category: "fast"
