name: CI - main - humanoid-flat-ground

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Run every day at midnight. Add another cron entry to run at a different time.
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ihmcrobotics/valkyrie/.github/workflows/version-dep-GradleCI-base.yml@main
    with:
      test-category: "humanoid-flat-ground"
