# This workflow is used as the base for the other workflows mean to be run on the main branch.
name: CI - main - base

on:
  workflow_call:
    inputs:
      test-category:
        description: 'Test category to run'
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: 8.5

      - name: Gradle test ${{ inputs.test-category }}
        run: gradle test -Pcategory=${{ inputs.test-category }}
